/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        'retro-brown': '#2A1208',
        'retro-dark': '#1C0B04',
        'cheddar-yellow': '#F59E0B',
        'sun-gold': '#FBBF24',
        'burnt-orange': '#D9531E',
        'buttermilk': '#FFF9F2',
        'cream-soft': '#FDF4E7',
        'sauce-red': '#DC2626',
        "on-primary-fixed":"#2f1505",
        "surface-container-lowest":"#ffffff",
        "error-container":"#ffdad6",
        "on-error-container":"#93000a",
        "secondary":"#835500",
        "surface":"#fff8f0",
        "on-error":"#ffffff",
        "on-tertiary-fixed-variant":"#004d65",
        "parchment-subtle":"#FBF4E8",
        "secondary-fixed":"#ffddb4",
        "on-secondary-fixed-variant":"#633f00",
        "outline-variant":"#d5c3bb",
        "on-primary":"#ffffff",
        "primary-fixed-dim":"#eebca3",
        "tertiary":"#000000",
        "primary-fixed":"#ffdbca",
        "surface-container-highest":"#e8e2d8",
        "surface-bright":"#fff8f0",
        "inverse-primary":"#eebca3",
        "on-background":"#1e1b16",
        "surface-variant":"#e8e2d8",
        "background":"#fff8f0",
        "tertiary-fixed-dim":"#80d1f6",
        "on-surface-variant":"#50443e",
        "parchment-border":"#E8DEC8",
        "on-tertiary-container":"#368daf",
        "primary-container":"#2f1505",
        "inverse-surface":"#33302a",
        "surface-container-high":"#eee7dd",
        "tomato-crimson":"#E63946",
        "primary":"#000000",
        "inverse-on-surface":"#f7f0e6",
        "charcoal-muted":"#7D786E",
        "on-surface":"#1e1b16",
        "on-tertiary-fixed":"#001f2a",
        "secondary-container":"#feae2c",
        "surface-container-low":"#faf3e9",
        "outline":"#83746d",
        "surface-container":"#f4ede3",
        "surface-tint":"#7c5641",
        "on-primary-container":"#a57a64",
        "on-tertiary":"#ffffff",
        "cheddar-amber":"#FFB800",
        "secondary-fixed-dim":"#ffb955",
        "brioche-deep":"#1F0D03",
        "on-secondary-container":"#6b4500",
        "tertiary-container":"#001f2a",
        "error":"#ba1a1a",
        "on-secondary-fixed":"#291800",
        "lettuce-teal":"#2A9D8F",
        "on-primary-fixed-variant":"#613f2c",
        "surface-dim":"#e0d9d0",
        "on-secondary":"#ffffff",
        "tertiary-fixed":"#bee9ff"
      },
      fontFamily: {
        funky: ['"Shrikhand"', 'cursive'],
        chunky: ['"Bungee"', 'sans-serif'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        "body-md":["Hanken Grotesk"],
        "label-badge":["Bricolage Grotesque"],
        "headline-lg-mobile":["Bricolage Grotesque"],
        "title-lg":["\"Source Serif 4\""],
        "headline-lg":["Bricolage Grotesque"],
        "headline-md":["\"Source Serif 4\""],
        "body-lg":["Hanken Grotesk"],
        "display-xl":["Bricolage Grotesque"],
        "label-hotel":["\"Source Serif 4\""],
        "display-xl-mobile":["Bricolage Grotesque"]
      },
      fontSize: {
        "body-md":["15px",{"lineHeight":"22px","fontWeight":"400"}],
        "label-badge":["13px",{"lineHeight":"16px","letterSpacing":"0.06em","fontWeight":"800"}],
        "headline-lg-mobile":["28px",{"lineHeight":"32px","letterSpacing":"-0.02em","fontWeight":"800"}],
        "title-lg":["22px",{"lineHeight":"28px","fontWeight":"600"}],
        "headline-lg":["44px",{"lineHeight":"48px","letterSpacing":"-0.02em","fontWeight":"800"}],
        "headline-md":["28px",{"lineHeight":"34px","letterSpacing":"-0.01em","fontWeight":"600"}],
        "body-lg":["18px",{"lineHeight":"26px","fontWeight":"500"}],
        "display-xl":["72px",{"lineHeight":"76px","letterSpacing":"-0.04em","fontWeight":"800"}],
        "label-hotel":["14px",{"lineHeight":"18px","letterSpacing":"0.02em","fontWeight":"600"}],
        "display-xl-mobile":["40px",{"lineHeight":"44px","letterSpacing":"-0.03em","fontWeight":"800"}]
      },
      borderRadius: {
        "DEFAULT":"0.25rem",
        "lg":"0.5rem",
        "xl":"0.75rem",
        "full":"9999px"
      },
      spacing: {
        "gutter-desktop":"2rem",
        "gutter-mobile":"1rem",
        "space-xs":"0.5rem",
        "container-max":"1280px",
        "space-xl":"2rem",
        "space-sm":"0.75rem",
        "space-3xl":"4.5rem",
        "space-2xl":"3rem",
        "space-2xs":"0.25rem",
        "space-lg":"1.5rem",
        "space-md":"1rem"
      },
      boxShadow: {
        'pop': '6px 6px 0px #2A1208',
        'pop-sm': '3px 3px 0px #2A1208',
        'pop-lg': '10px 10px 0px #2A1208',
        'soft-glow': '0 20px 40px -15px rgba(245, 158, 11, 0.35)',
        'float-card': '0 25px 50px -12px rgba(42, 18, 8, 0.12)',
      }
    }
  },
  plugins: [],
}
